"""Snapshot tests for the SKILL.md and replay.py emitters.

These tests assert byte-stable output — if the emitter changes shape, the
fixture below must be updated and any downstream regenerations re-run.
"""

from __future__ import annotations

import ast

from skill_forge.codify.replay_script import skill_to_replay_py
from skill_forge.codify.skill_md import skill_to_md
from skill_forge.pipeline.schema import VALID_ACTIONS, Parameter, Skill, Step


def _hello_skill() -> Skill:
    return Skill(
        name="hello",
        description="Say hello",
        parameters=[
            Parameter(
                name="name", type="string", description="who to greet", default=None
            )
        ],
        steps=[
            Step(
                name="Launch app",
                action="app_launch",
                selector=None,
                args={"bundle_id": "com.example.app"},
                assertions=[],
            ),
            Step(
                name="Type greeting",
                action="type",
                selector=None,
                args={"text": "hello ${name}"},
                assertions=[],
            ),
        ],
    )


# -------------------------------------------------------------- schema gates

def test_valid_actions_is_frozen():
    assert VALID_ACTIONS == frozenset(
        {"click", "type", "press_key", "wait", "app_launch"}
    )


def test_step_fields_are_exactly_the_contract():
    s = Step(name="x", action="click", selector="AXButton", args={}, assertions=[])
    assert {"name", "action", "selector", "args", "assertions"} == set(s.__dict__)


def test_parameter_fields_are_exactly_the_contract():
    p = Parameter(name="a", type="string", description="d", default=None)
    assert {"name", "type", "description", "default"} == set(p.__dict__)


def test_skill_fields_are_exactly_the_contract():
    sk = Skill(name="n", description="d", parameters=[], steps=[])
    assert {"name", "description", "parameters", "steps"} == set(sk.__dict__)


# ---------------------------------------------------------------- skill_to_md

EXPECTED_MD = """\
---
name: hello
description: Say hello
---

# hello

Say hello

## Parameters
- `name` (string, required): who to greet

## How to invoke
Run: `forge replay <this-dir> --params '{"name": "..."}'`

## Steps (for reference; replay.py is the source of truth)
1. Launch app
2. Type greeting
"""


def test_skill_to_md_byte_stable():
    assert skill_to_md(_hello_skill()) == EXPECTED_MD


def test_skill_to_md_no_parameters():
    skill = Skill(name="x", description="y", parameters=[], steps=[])
    out = skill_to_md(skill)
    assert "## Parameters\n(none)" in out
    assert "--params '{}'" in out


def test_skill_to_md_with_default():
    skill = Skill(
        name="x",
        description="y",
        parameters=[
            Parameter(name="n", type="number", description="d", default="42")
        ],
        steps=[],
    )
    out = skill_to_md(skill)
    assert "- `n` (number, default=42): d" in out
    assert '--params \'{"n": 42}\'' in out


# --------------------------------------------------------- skill_to_replay_py

EXPECTED_PY = '''\
"""Auto-generated by skill_forge.codify — do not edit by hand.

Skill: hello
Say hello
"""

from __future__ import annotations

import argparse
import json
import re
import sys

from skill_forge.replay.actions import app_launch, click, press_key, type_text, wait
from skill_forge.replay.ax_resolve import find  # noqa: F401  (used by hand-edits)


_PLACEHOLDER_RE = re.compile(r"\\$\\{([a-zA-Z_][a-zA-Z0-9_]*)\\}")


def _subst(template: str, params: dict) -> str:
    def repl(match):
        key = match.group(1)
        if key not in params:
            raise KeyError(f"missing parameter: {key}")
        return str(params[key])
    return _PLACEHOLDER_RE.sub(repl, template)


def main() -> int:
    parser = argparse.ArgumentParser(description='hello')
    parser.add_argument("--params", required=True, help="JSON dict of parameters.")
    args = parser.parse_args()
    params = json.loads(args.params)
    for required in ["name"]:
        if required not in params:
            print(f"missing required parameter: {required}", file=sys.stderr)
            return 2

    # Launch app
    app_launch('com.example.app')
    # Type greeting
    type_text(_subst('hello ${name}', params))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def test_skill_to_replay_py_byte_stable():
    assert skill_to_replay_py(_hello_skill()) == EXPECTED_PY


def test_skill_to_replay_py_is_valid_python():
    ast.parse(skill_to_replay_py(_hello_skill()))


def test_emitted_replay_preserves_placeholder_syntax():
    out = skill_to_replay_py(_hello_skill())
    assert "${name}" in out
    assert "$\\{name\\}" not in out  # not over-escaped


def test_handwritten_calculator_skill_md_parses():
    """The hand-written fixture is the truth-test for Phase 4. At minimum it
    must have YAML frontmatter and the documented sections."""
    text = (
        __import__("pathlib").Path("examples/calculator_handwritten/SKILL.md").read_text()
    )
    assert text.startswith("---\nname: calculator-add\n")
    assert "## Parameters" in text
    assert "## How to invoke" in text
    assert "## Steps" in text
    assert "${a}" in text and "${b}" in text


def test_handwritten_calculator_replay_is_valid_python():
    src = __import__("pathlib").Path(
        "examples/calculator_handwritten/scripts/replay.py"
    ).read_text()
    ast.parse(src)
    assert "from skill_forge.replay.actions" in src
    assert "from skill_forge.replay.ax_resolve" in src
