"""Render a Skill to a self-contained scripts/replay.py.

The generated script imports skill_forge.replay.actions and
skill_forge.replay.ax_resolve. Those modules ship in Phase 4 — until then
the generated script is syntactically valid Python that won't run.
"""

from __future__ import annotations

import json

from skill_forge.pipeline.schema import Skill, Step

_ACTION_DISPATCH: dict[str, str] = {
    "click": "click(_subst({selector!r}, params))",
    "type": "type_text(_subst({text!r}, params))",
    "press_key": "press_key({keycode!r}, modifiers={modifiers!r})",
    "wait": "wait({seconds!r})",
    "app_launch": "app_launch({bundle_id!r})",
}


def skill_to_replay_py(skill: Skill) -> str:
    required = [p.name for p in skill.parameters if p.default is None]
    body_lines = [_step_call(step) for step in skill.steps]
    body = "\n    ".join(body_lines) if body_lines else "pass"
    return _TEMPLATE.format(
        skill_name=skill.name,
        skill_description=skill.description,
        required_json=json.dumps(required),
        steps_body=body,
    )


def _step_call(step: Step) -> str:
    if step.action == "click":
        sel = step.selector or ""
        return f"# {step.name}\n    click(_subst({sel!r}, params))"
    if step.action == "type":
        text = step.args.get("text", "")
        return f"# {step.name}\n    type_text(_subst({text!r}, params))"
    if step.action == "press_key":
        keycode = step.args.get("keycode")
        mods = step.args.get("modifiers", [])
        return f"# {step.name}\n    press_key({keycode!r}, modifiers={mods!r})"
    if step.action == "wait":
        seconds = step.args.get("seconds", 0.0)
        return f"# {step.name}\n    wait({seconds!r})"
    if step.action == "app_launch":
        bundle = step.args.get("bundle_id", "")
        return f"# {step.name}\n    app_launch({bundle!r})"
    return f"# UNKNOWN ACTION {step.action!r}: {step.name}\n    pass"


_TEMPLATE = '''\
"""Auto-generated by skill_forge.codify — do not edit by hand.

Skill: {skill_name}
{skill_description}
"""

from __future__ import annotations

import argparse
import json
import re
import sys

from skill_forge.replay.actions import app_launch, click, press_key, type_text, wait
from skill_forge.replay.ax_resolve import find  # noqa: F401  (used by hand-edits)


_PLACEHOLDER_RE = re.compile(r"\\$\\{{([a-zA-Z_][a-zA-Z0-9_]*)\\}}")


def _subst(template: str, params: dict) -> str:
    def repl(match):
        key = match.group(1)
        if key not in params:
            raise KeyError(f"missing parameter: {{key}}")
        return str(params[key])
    return _PLACEHOLDER_RE.sub(repl, template)


def main() -> int:
    parser = argparse.ArgumentParser(description={skill_name!r})
    parser.add_argument("--params", required=True, help="JSON dict of parameters.")
    args = parser.parse_args()
    params = json.loads(args.params)
    for required in {required_json}:
        if required not in params:
            print(f"missing required parameter: {{required}}", file=sys.stderr)
            return 2

    {steps_body}
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''
