"""Auto-generated by skill_forge.codify — do not edit by hand.

Skill: send-email
Sends a new email with specified recipient, subject, and body using the Mail app
"""

from __future__ import annotations

import argparse
import json
import re
import sys

from skill_forge.replay.actions import app_launch, click, press_key, type_text, wait
from skill_forge.replay.ax_resolve import find  # noqa: F401  (used by hand-edits)


_PLACEHOLDER_RE = re.compile(r"\$\{([a-zA-Z_][a-zA-Z0-9_]*)\}")


def _subst(template: str, params: dict) -> str:
    def repl(match):
        key = match.group(1)
        if key not in params:
            raise KeyError(f"missing parameter: {key}")
        return str(params[key])
    return _PLACEHOLDER_RE.sub(repl, template)


def main() -> int:
    parser = argparse.ArgumentParser(description='send-email')
    parser.add_argument("--params", required=True, help="JSON dict of parameters.")
    args = parser.parse_args()
    params = json.loads(args.params)
    for required in []:
        if required not in params:
            print(f"missing required parameter: {required}", file=sys.stderr)
            return 2

    # Launch Mail app
    app_launch('com.apple.mail')
    # Wait for window to appear
    wait(1.5)
    # Open new message
    press_key(45, modifiers=['cmd'])
    # Type recipient email
    type_text(_subst('${recipient}', params))
    # Click on subject field
    click(_subst("AXApplication[bundle='com.apple.mail']/AXWindow[id='_NS:41'; title='New Message']/AXTextField[id='Mail.subjectField']", params))
    # Type email subject
    type_text(_subst('${subject}', params))
    # Move to email body field
    press_key(48, modifiers=[])
    # Type email body
    type_text(_subst('${body}', params))
    return 0


if __name__ == "__main__":
    sys.exit(main())
